import { defineConfig } from 'vitepress';
import { fileURLToPath, URL } from 'node:url';

export default defineConfig({
  // Project page on GitHub Pages → served under /CatalystEngine/.
  // CI sets DOCS_BASE; locally it stays '/' for convenience.
  base: process.env.DOCS_BASE || '/',
  lang: 'en-US',
  title: 'CatalystEngine',
  description:
    'Data-driven, polymorphic, plug-and-play progression engine for TypeScript and PhaserJS',
  lastUpdated: true,
  cleanUrls: true,

  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/introduction' },
      { text: 'API', link: '/api/catalyst-engine' },
      { text: 'Playground', link: '/playground' },
      {
        text: 'v1.0.0',
        items: [
          { text: 'Changelog', link: 'https://github.com/3xl/CatalystEngine/releases' },
          { text: 'Repository', link: 'https://github.com/3xl/CatalystEngine' },
        ],
      },
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Getting started',
          items: [
            { text: 'Introduction', link: '/guide/introduction' },
            { text: 'Installation', link: '/guide/installation' },
            { text: 'Quick start', link: '/guide/quick-start' },
          ],
        },
        {
          text: 'Concepts',
          items: [
            { text: 'Architecture', link: '/guide/architecture' },
            { text: 'Stats and modifiers', link: '/guide/stats' },
            { text: 'Experience and levels', link: '/guide/experience' },
            { text: 'Skill tree', link: '/guide/skill-tree' },
            { text: 'Event Bus', link: '/guide/events' },
            { text: 'Persistence', link: '/guide/persistence' },
          ],
        },
        {
          text: 'Examples',
          items: [
            { text: 'Mini RPG (full demo)', link: '/guide/full-example' },
          ],
        },
      ],
      '/api/': [
        {
          text: 'API reference',
          items: [
            { text: 'CatalystEngine', link: '/api/catalyst-engine' },
            { text: 'StatManager', link: '/api/stat-manager' },
            { text: 'ExperienceManager', link: '/api/experience-manager' },
            { text: 'SkillManager', link: '/api/skill-manager' },
            { text: 'EngineEventBus', link: '/api/event-bus' },
            { text: 'Interfaces and types', link: '/api/interfaces' },
          ],
        },
      ],
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/3xl/CatalystEngine' },
    ],

    search: { provider: 'local' },

    footer: {
      message: 'Released under the MIT License.',
      copyright: 'CatalystEngine',
    },

    docFooter: {
      prev: 'Previous page',
      next: 'Next page',
    },

    outline: { label: 'On this page' },
  },

  vite: {
    resolve: {
      alias: {
        // Demos import from 'catalyst-engine' like a real user would.
        // Since the package IS this project, we resolve it to the local dist
        // (regenerated by the predocs:* hooks before dev/build).
        'catalyst-engine': fileURLToPath(
          new URL('../../dist/index.mjs', import.meta.url)
        ),
      },
    },
    // Phaser must not be pre-bundled at build time: it is imported dynamically
    // on the client only, inside DemoCanvas.vue.
    ssr: { noExternal: ['phaser'] },
  },
});
